name: Using secret and variables
on:
  workflow_call:
    secrets: # reusable workflows do not have direct access to secrets, we have to pass them from the caller
      repo_s:
        required: true
      org_s:
        required: true
jobs:
  use_secrets_and_vars:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ secrets.repo_s }}
      - run: echo ${{ secrets.org_s }}
   #   - run: echo ${{secrets.org_s=='orgsecret'}} # this is a way to test if the secret value has been passed correctly
   #   - run: echo ${{secrets.org_s}} | sed 's/./& /g' # prints the secret for test; use only for a dummy secret.
      - run: echo ${{vars.repo_var}}
      - run: echo done with secrets and variables
