name: Useage of inputs, secrets, and outputs
on:
  workflow_call:
    outputs:
      firstword:
        description: "The first output string"
        value: ${{ jobs.set_outputs.outputs.output1 }}
      secondword:
        description: "The second output string"
        value: ${{ jobs.set_outputs.outputs.output2 }}
jobs:
  use_inputs_and_secrets:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.envPAT }}
        configuration-path: ${{ inputs.config-path }}
    - run: echo ${{ secrets.envPAT }}
    - run: echo ${{ inputs.config-path }}
    - run: echo secrets and inputs job done
  set_outputs:
    name: Generate output
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.output1 }}
      output2: ${{ steps.step2.outputs.output2 }}
    steps:
      - id: step1
        run: echo "output1=hello" >> $GITHUB_OUTPUT
      - id: step2
        run: echo "output2=world" >> $GITHUB_OUTPUT 

  print_to_console:
   name: print ouputs
   runs-on: ubuntu-latest
   needs: [set_outputs]
   steps:
    - run: echo '${{ toJSON(needs.example_job.outputs) }}'
    - run: echo done with test.yml reusable workflow